#
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Huawei Inc.
#
name: xpanse-website-ci

# Run this workflow every time a new commit push to the repository
on:
    pull_request:
        branches: ['main']

jobs:
    build:
        permissions:
            checks: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - run: |
                  venv="$HOME/.local/share/venv"
                  python3 -m venv "$venv"
                  echo "$venv/bin" >> $GITHUB_PATH
            - name: Install Dependencies
              working-directory: ./
              run: npm install
            - name: Check if package-lock.json is up to date
              run: npx --yes package-lock-utd@1.1.3
            - name: Run vale linter
              uses: errata-ai/vale-action@reviewdog
              with:
                  filter_mode: nofilter
                  fail_on_error: true
            - name: Run EsLint
              working-directory: ./
              run: npx eslint . --max-warnings=0
            - name: Check Prettier Format
              working-directory: ./
              run: npx prettier --config .prettierrc --check .
            - name: Run TS compiler
              working-directory: ./
              run: tsc
            - name: Run build
              working-directory: ./
              run: npm run build
